### ISSUE TITLE
How to make code more protective?

### ISSUE THREAD

**Issue by weziye** [codesbiome/electron-react-webpack-typescript-2024#67]
When I finish developing the project, I want the code to be protected. I tried adding bytenode-webpack-plugin and asarmor to the project, but they failed. Can you provide a solution? Thanks

**Comment by codesbiome** [comment]
For compiling output javascript into bytecode, have you tried using these examples for configuring the project:
https://github.com/herberttn/bytenode-webpack-plugin/tree/main/examples

**Comment by weziye** [comment]
I compiled the backend code into bytecode and it ran successfully, but I couldn't compile the rendering resources into bytecode
