### ISSUE TITLE
White screen in app after npm run make

### ISSUE THREAD

**Issue by dotinto** [codesbiome/electron-react-webpack-typescript-2024#68]
In dev environment app is work correctly, but after making it displays white screen only.
Using Dev Tools i had received that div.app is empty.

If launch exe in package folder, received the same issue.

Note:
Path to app dir contain no spaces and non-latinic symbols
Console didn't threw any errors
![image](https://github.com/codesbiome/electron-react-webpack-typescript-2024/assets/93837399/d931f24a-36ea-409c-af71-f5c3d557e392)

Screenshot :)
![image](https://github.com/codesbiome/electron-react-webpack-typescript-2024/assets/93837399/fac6793e-19b6-42b0-a75f-8872a1b60998)

**Comment by codesbiome** [comment]
Can you advise which command was used to build the executable? 
Usually `npm run package` should work just fine.

**Comment by dotinto** [comment]
> Can you advise which command was used to build the executable? Usually `npm run package` should work just fine.

I use `npm run make`

**Comment by dotinto** [comment]
> > Can you advise which command was used to build the executable? Usually `npm run package` should work just fine.
> 
> I use `npm run make` but i will try `npm run package`

nothing else happened(

**Comment by dotinto** [comment]
I think something happened with the rendering

**Comment by codesbiome** [comment]
Can you share any repository link (based on this project) to replicate the issue you receiving?

**Comment by dotinto** [comment]
> Can you share any repository link (based on this project) to replicate the issue you receiving?
